<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;
use App\Models\Backend\TimeZone;
use Modules\Sale\Models\Customer;
use Modules\Configuration\Models\Outlet;
use Modules\Configuration\Models\Company;
use Modules\Accounting\Models\PaymentMethod;

class ConfigurationSeeder extends Seeder
{
    public function run()
    {
        Company::create([
            'business_name' => 'Fresh Mart',
            'short_name' => 'F M',
            'email' => 'admin@example.com',
            'phone' => '+880 18 123 91633',
            'date_format' => 'Y/m/d',       
            'zone_name' => 'Asia/Dhaka',
            'currency' => '$',
            'currency_position' => 'Before Amount',
            'precision' => '2',
            'default_customer' => '1',
            'default_cursor_position' => 'Barcode Box',
            'product_display' => 'Image View',
            'default_payment' => '1',
            'inv_logo_is_show' => 'Yes',
            'invoice_logo' => '',
            'installment_days' => '3',
            'minimum_point_to_redeem' => '0',
            'loyalty_rate' => '0',
            'e_commerce_checker' => 'Yes',
            'product_code_start_from' => '000001',
            'white_label' => json_encode([
                'site_name' => 'Rashan Ki Dukan',
                'site_footer' => 'Rashan Ki Dukan',
                'site_title' => 'Door Soft',
                'site_link' => 'https://rashankidukan.com',
                'site_logo' => 'initial-logo.png',
                'site_favicon' => 'initial-fav.ico',
            ]),
            'collect_tax' => 'Yes',
            'tax_is_gst' => 'Yes',
            'tax_title' => 'Local Tax',
            'tax_registration_no' => '100666666666666',
            'del_status' => 'Live'
        ]);

        Customer::create([
            'name' => 'Walk-in Customer',
            'company_id' => 1,
            'del_status' => 'Live'
        ]);
        Outlet::create([
            'outlet_name' => 'ABC',
            'outlet_code' => '000001',
            'phone' => '01709-098765',
            'email' => 'abc@email.com',
            'address' => 'Uttara, Dhaka',
            'user_id' => 1,
            'company_id' => 1,
            'del_status' => 'Live'
        ]);

        $paymentMethods = [
            ['name' => 'Cash', 'account_type' => 'Cash'],
            ['name' => 'Bank', 'account_type' => 'Bank_Account'], 
            ['name' => 'Paypal', 'account_type' => 'Paypal'],
            ['name' => 'Stripe', 'account_type' => 'Stripe'],
            ['name' => 'Loyalty Point', 'account_type' => 'Loyalty Point']
        ];

        foreach ($paymentMethods as $index => $method) {
            PaymentMethod::create([
                'name' => $method['name'],
                'account_type' => $method['account_type'],
                'status' => 'Enable',
                'is_deletable' => 'No',
                'sort_id' => $index + 1,
                'company_id' => 1,
                'del_status' => 'Live'
            ]);
        }



        TimeZone::insert([
            ['id' => 1, 'country_code' => 'AD', 'zone_name' => 'Europe/Andorra', 'del_status' => 'Live'],
            ['id' => 2, 'country_code' => 'AE', 'zone_name' => 'Asia/Dubai', 'del_status' => 'Live'],
            ['id' => 3, 'country_code' => 'AF', 'zone_name' => 'Asia/Kabul', 'del_status' => 'Live'],
            ['id' => 4, 'country_code' => 'AG', 'zone_name' => 'America/Antigua', 'del_status' => 'Live'],
            ['id' => 5, 'country_code' => 'AI', 'zone_name' => 'America/Anguilla', 'del_status' => 'Live'],
            ['id' => 6, 'country_code' => 'AL', 'zone_name' => 'Europe/Tirane', 'del_status' => 'Live'],
            ['id' => 7, 'country_code' => 'AM', 'zone_name' => 'Asia/Yerevan', 'del_status' => 'Live'],
            ['id' => 8, 'country_code' => 'AO', 'zone_name' => 'Africa/Luanda', 'del_status' => 'Live'],
            ['id' => 9, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/McMurdo', 'del_status' => 'Live'],
            ['id' => 10, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Casey', 'del_status' => 'Live'],
            ['id' => 11, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Davis', 'del_status' => 'Live'],
            ['id' => 12, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/DumontDUrville', 'del_status' => 'Live'],
            ['id' => 13, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Mawson', 'del_status' => 'Live'],
            ['id' => 14, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Palmer', 'del_status' => 'Live'],
            ['id' => 15, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Rothera', 'del_status' => 'Live'],
            ['id' => 16, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Syowa', 'del_status' => 'Live'],
            ['id' => 17, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Troll', 'del_status' => 'Live'],
            ['id' => 18, 'country_code' => 'AQ', 'zone_name' => 'Antarctica/Vostok', 'del_status' => 'Live'],
            ['id' => 19, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Buenos_Aires', 'del_status' => 'Live'],
            ['id' => 20, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Cordoba', 'del_status' => 'Live'],
            ['id' => 21, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Salta', 'del_status' => 'Live'],
            ['id' => 22, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Jujuy', 'del_status' => 'Live'],
            ['id' => 23, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Tucuman', 'del_status' => 'Live'],
            ['id' => 24, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Catamarca', 'del_status' => 'Live'],
            ['id' => 25, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/La_Rioja', 'del_status' => 'Live'],
            ['id' => 26, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/San_Juan', 'del_status' => 'Live'],
            ['id' => 27, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Mendoza', 'del_status' => 'Live'],
            ['id' => 28, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/San_Luis', 'del_status' => 'Live'],
            ['id' => 29, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Rio_Gallegos', 'del_status' => 'Live'],
            ['id' => 30, 'country_code' => 'AR', 'zone_name' => 'America/Argentina/Ushuaia', 'del_status' => 'Live'],
            ['id' => 31, 'country_code' => 'AS', 'zone_name' => 'Pacific/Pago_Pago', 'del_status' => 'Live'],
            ['id' => 32, 'country_code' => 'AT', 'zone_name' => 'Europe/Vienna', 'del_status' => 'Live'],
            ['id' => 33, 'country_code' => 'AU', 'zone_name' => 'Australia/Lord_Howe', 'del_status' => 'Live'],
            ['id' => 34, 'country_code' => 'AU', 'zone_name' => 'Antarctica/Macquarie', 'del_status' => 'Live'],
            ['id' => 35, 'country_code' => 'AU', 'zone_name' => 'Australia/Hobart', 'del_status' => 'Live'],
            ['id' => 36, 'country_code' => 'AU', 'zone_name' => 'Australia/Currie', 'del_status' => 'Live'],
            ['id' => 37, 'country_code' => 'AU', 'zone_name' => 'Australia/Melbourne', 'del_status' => 'Live'],
            ['id' => 38, 'country_code' => 'AU', 'zone_name' => 'Australia/Sydney', 'del_status' => 'Live'],
            ['id' => 39, 'country_code' => 'AU', 'zone_name' => 'Australia/Broken_Hill', 'del_status' => 'Live'],
            ['id' => 40, 'country_code' => 'AU', 'zone_name' => 'Australia/Brisbane', 'del_status' => 'Live'],
            ['id' => 41, 'country_code' => 'AU', 'zone_name' => 'Australia/Lindeman', 'del_status' => 'Live'],
            ['id' => 42, 'country_code' => 'AU', 'zone_name' => 'Australia/Adelaide', 'del_status' => 'Live'],
            ['id' => 43, 'country_code' => 'AU', 'zone_name' => 'Australia/Darwin', 'del_status' => 'Live'],
            ['id' => 44, 'country_code' => 'AU', 'zone_name' => 'Australia/Perth', 'del_status' => 'Live'],
            ['id' => 45, 'country_code' => 'AU', 'zone_name' => 'Australia/Eucla', 'del_status' => 'Live'],
            ['id' => 46, 'country_code' => 'AW', 'zone_name' => 'America/Aruba', 'del_status' => 'Live'],
            ['id' => 47, 'country_code' => 'AX', 'zone_name' => 'Europe/Mariehamn', 'del_status' => 'Live'],
            ['id' => 48, 'country_code' => 'AZ', 'zone_name' => 'Asia/Baku', 'del_status' => 'Live'],
            ['id' => 49, 'country_code' => 'BA', 'zone_name' => 'Europe/Sarajevo', 'del_status' => 'Live'],
            ['id' => 50, 'country_code' => 'BB', 'zone_name' => 'America/Barbados', 'del_status' => 'Live'],
            ['id' => 51, 'country_code' => 'BD', 'zone_name' => 'Asia/Dhaka', 'del_status' => 'Live'],
            ['id' => 52, 'country_code' => 'BE', 'zone_name' => 'Europe/Brussels', 'del_status' => 'Live'],
            ['id' => 53, 'country_code' => 'BF', 'zone_name' => 'Africa/Ouagadougou', 'del_status' => 'Live'],
            ['id' => 54, 'country_code' => 'BG', 'zone_name' => 'Europe/Sofia', 'del_status' => 'Live'],
            ['id' => 55, 'country_code' => 'BH', 'zone_name' => 'Asia/Bahrain', 'del_status' => 'Live'],
            ['id' => 56, 'country_code' => 'BI', 'zone_name' => 'Africa/Bujumbura', 'del_status' => 'Live'],
            ['id' => 57, 'country_code' => 'BJ', 'zone_name' => 'Africa/Porto-Novo', 'del_status' => 'Live'],
            ['id' => 58, 'country_code' => 'BL', 'zone_name' => 'America/St_Barthelemy', 'del_status' => 'Live'],
            ['id' => 59, 'country_code' => 'BM', 'zone_name' => 'Atlantic/Bermuda', 'del_status' => 'Live'],
            ['id' => 60, 'country_code' => 'BN', 'zone_name' => 'Asia/Brunei', 'del_status' => 'Live'],
            ['id' => 61, 'country_code' => 'BO', 'zone_name' => 'America/La_Paz', 'del_status' => 'Live'],
            ['id' => 62, 'country_code' => 'BQ', 'zone_name' => 'America/Kralendijk', 'del_status' => 'Live'],
            ['id' => 63, 'country_code' => 'BR', 'zone_name' => 'America/Noronha', 'del_status' => 'Live'],
            ['id' => 64, 'country_code' => 'BR', 'zone_name' => 'America/Belem', 'del_status' => 'Live'],
            ['id' => 65, 'country_code' => 'BR', 'zone_name' => 'America/Fortaleza', 'del_status' => 'Live'],
            ['id' => 66, 'country_code' => 'BR', 'zone_name' => 'America/Recife', 'del_status' => 'Live'],
            ['id' => 67, 'country_code' => 'BR', 'zone_name' => 'America/Araguaina', 'del_status' => 'Live'],
            ['id' => 68, 'country_code' => 'BR', 'zone_name' => 'America/Maceio', 'del_status' => 'Live'],
            ['id' => 69, 'country_code' => 'BR', 'zone_name' => 'America/Bahia', 'del_status' => 'Live'],
            ['id' => 70, 'country_code' => 'BR', 'zone_name' => 'America/Sao_Paulo', 'del_status' => 'Live'],
            ['id' => 71, 'country_code' => 'BR', 'zone_name' => 'America/Campo_Grande', 'del_status' => 'Live'],
            ['id' => 72, 'country_code' => 'BR', 'zone_name' => 'America/Cuiaba', 'del_status' => 'Live'],
            ['id' => 73, 'country_code' => 'BR', 'zone_name' => 'America/Santarem', 'del_status' => 'Live'],
            ['id' => 74, 'country_code' => 'BR', 'zone_name' => 'America/Porto_Velho', 'del_status' => 'Live'],
            ['id' => 75, 'country_code' => 'BR', 'zone_name' => 'America/Boa_Vista', 'del_status' => 'Live'],
            ['id' => 76, 'country_code' => 'BR', 'zone_name' => 'America/Manaus', 'del_status' => 'Live'],
            ['id' => 77, 'country_code' => 'BR', 'zone_name' => 'America/Eirunepe', 'del_status' => 'Live'],
            ['id' => 78, 'country_code' => 'BR', 'zone_name' => 'America/Rio_Branco', 'del_status' => 'Live'],
            ['id' => 79, 'country_code' => 'BS', 'zone_name' => 'America/Nassau', 'del_status' => 'Live'],
            ['id' => 80, 'country_code' => 'BT', 'zone_name' => 'Asia/Thimphu', 'del_status' => 'Live'],
            ['id' => 81, 'country_code' => 'BW', 'zone_name' => 'Africa/Gaborone', 'del_status' => 'Live'],
            ['id' => 82, 'country_code' => 'BY', 'zone_name' => 'Europe/Minsk', 'del_status' => 'Live'],
            ['id' => 83, 'country_code' => 'BZ', 'zone_name' => 'America/Belize', 'del_status' => 'Live'],
            ['id' => 84, 'country_code' => 'CA', 'zone_name' => 'America/St_Johns', 'del_status' => 'Live'],
            ['id' => 85, 'country_code' => 'CA', 'zone_name' => 'America/Halifax', 'del_status' => 'Live'],
            ['id' => 86, 'country_code' => 'CA', 'zone_name' => 'America/Glace_Bay', 'del_status' => 'Live'],
            ['id' => 87, 'country_code' => 'CA', 'zone_name' => 'America/Moncton', 'del_status' => 'Live'],
            ['id' => 88, 'country_code' => 'CA', 'zone_name' => 'America/Goose_Bay', 'del_status' => 'Live'],
            ['id' => 89, 'country_code' => 'CA', 'zone_name' => 'America/Blanc-Sablon', 'del_status' => 'Live'],
            ['id' => 90, 'country_code' => 'CA', 'zone_name' => 'America/Toronto', 'del_status' => 'Live'],
            ['id' => 91, 'country_code' => 'CA', 'zone_name' => 'America/Nipigon', 'del_status' => 'Live'],
            ['id' => 92, 'country_code' => 'CA', 'zone_name' => 'America/Thunder_Bay', 'del_status' => 'Live'],
            ['id' => 93, 'country_code' => 'CA', 'zone_name' => 'America/Iqaluit', 'del_status' => 'Live'],
            ['id' => 94, 'country_code' => 'CA', 'zone_name' => 'America/Pangnirtung', 'del_status' => 'Live'],
            ['id' => 95, 'country_code' => 'CA', 'zone_name' => 'America/Atikokan', 'del_status' => 'Live'],
            ['id' => 96, 'country_code' => 'CA', 'zone_name' => 'America/Winnipeg', 'del_status' => 'Live'],
            ['id' => 97, 'country_code' => 'CA', 'zone_name' => 'America/Rainy_River', 'del_status' => 'Live'],
            ['id' => 98, 'country_code' => 'CA', 'zone_name' => 'America/Resolute', 'del_status' => 'Live'],
            ['id' => 99, 'country_code' => 'CA', 'zone_name' => 'America/Rankin_Inlet', 'del_status' => 'Live'],
            ['id' => 100, 'country_code' => 'CA', 'zone_name' => 'America/Regina', 'del_status' => 'Live'],
            ['id' => 101, 'country_code' => 'CA', 'zone_name' => 'America/Swift_Current', 'del_status' => 'Live'],
            ['id' => 102, 'country_code' => 'CA', 'zone_name' => 'America/Edmonton', 'del_status' => 'Live'],
            ['id' => 103, 'country_code' => 'CA', 'zone_name' => 'America/Cambridge_Bay', 'del_status' => 'Live'],
            ['id' => 104, 'country_code' => 'CA', 'zone_name' => 'America/Yellowknife', 'del_status' => 'Live'],
            ['id' => 105, 'country_code' => 'CA', 'zone_name' => 'America/Inuvik', 'del_status' => 'Live'],
            ['id' => 106, 'country_code' => 'CA', 'zone_name' => 'America/Creston', 'del_status' => 'Live'],
            ['id' => 107, 'country_code' => 'CA', 'zone_name' => 'America/Dawson_Creek', 'del_status' => 'Live'],
            ['id' => 108, 'country_code' => 'CA', 'zone_name' => 'America/Fort_Nelson', 'del_status' => 'Live'],
            ['id' => 109, 'country_code' => 'CA', 'zone_name' => 'America/Vancouver', 'del_status' => 'Live'],
            ['id' => 110, 'country_code' => 'CA', 'zone_name' => 'America/Whitehorse', 'del_status' => 'Live'],
            ['id' => 111, 'country_code' => 'CA', 'zone_name' => 'America/Dawson', 'del_status' => 'Live'],
            ['id' => 112, 'country_code' => 'CC', 'zone_name' => 'Indian/Cocos', 'del_status' => 'Live'],
            ['id' => 113, 'country_code' => 'CD', 'zone_name' => 'Africa/Kinshasa', 'del_status' => 'Live'],
            ['id' => 114, 'country_code' => 'CD', 'zone_name' => 'Africa/Lubumbashi', 'del_status' => 'Live'],
            ['id' => 115, 'country_code' => 'CF', 'zone_name' => 'Africa/Bangui', 'del_status' => 'Live'],
            ['id' => 116, 'country_code' => 'CG', 'zone_name' => 'Africa/Brazzaville', 'del_status' => 'Live'],
            ['id' => 117, 'country_code' => 'CH', 'zone_name' => 'Europe/Zurich', 'del_status' => 'Live'],
            ['id' => 118, 'country_code' => 'CI', 'zone_name' => 'Africa/Abidjan', 'del_status' => 'Live'],
            ['id' => 119, 'country_code' => 'CK', 'zone_name' => 'Pacific/Rarotonga', 'del_status' => 'Live'],
            ['id' => 120, 'country_code' => 'CL', 'zone_name' => 'America/Santiago', 'del_status' => 'Live'],
            ['id' => 121, 'country_code' => 'CL', 'zone_name' => 'America/Punta_Arenas', 'del_status' => 'Live'],
            ['id' => 122, 'country_code' => 'CL', 'zone_name' => 'Pacific/Easter', 'del_status' => 'Live'],
            ['id' => 123, 'country_code' => 'CM', 'zone_name' => 'Africa/Douala', 'del_status' => 'Live'],
            ['id' => 124, 'country_code' => 'CN', 'zone_name' => 'Asia/Shanghai', 'del_status' => 'Live'],
            ['id' => 125, 'country_code' => 'CN', 'zone_name' => 'Asia/Urumqi', 'del_status' => 'Live'],
            ['id' => 126, 'country_code' => 'CO', 'zone_name' => 'America/Bogota', 'del_status' => 'Live'],
            ['id' => 127, 'country_code' => 'CR', 'zone_name' => 'America/Costa_Rica', 'del_status' => 'Live'],
            ['id' => 128, 'country_code' => 'CU', 'zone_name' => 'America/Havana', 'del_status' => 'Live'],
            ['id' => 129, 'country_code' => 'CV', 'zone_name' => 'Atlantic/Cape_Verde', 'del_status' => 'Live'],
            ['id' => 130, 'country_code' => 'CW', 'zone_name' => 'America/Curacao', 'del_status' => 'Live'],
            ['id' => 131, 'country_code' => 'CX', 'zone_name' => 'Indian/Christmas', 'del_status' => 'Live'],
            ['id' => 132, 'country_code' => 'CY', 'zone_name' => 'Asia/Nicosia', 'del_status' => 'Live'],
            ['id' => 133, 'country_code' => 'CY', 'zone_name' => 'Asia/Famagusta', 'del_status' => 'Live'],
            ['id' => 134, 'country_code' => 'CZ', 'zone_name' => 'Europe/Prague', 'del_status' => 'Live'],
            ['id' => 135, 'country_code' => 'DE', 'zone_name' => 'Europe/Berlin', 'del_status' => 'Live'],
            ['id' => 136, 'country_code' => 'DE', 'zone_name' => 'Europe/Busingen', 'del_status' => 'Live'],
            ['id' => 137, 'country_code' => 'DJ', 'zone_name' => 'Africa/Djibouti', 'del_status' => 'Live'],
            ['id' => 138, 'country_code' => 'DK', 'zone_name' => 'Europe/Copenhagen', 'del_status' => 'Live'],
            ['id' => 139, 'country_code' => 'DM', 'zone_name' => 'America/Dominica', 'del_status' => 'Live'],
            ['id' => 140, 'country_code' => 'DO', 'zone_name' => 'America/Santo_Domingo', 'del_status' => 'Live'],
            ['id' => 141, 'country_code' => 'DZ', 'zone_name' => 'Africa/Algiers', 'del_status' => 'Live'],
            ['id' => 142, 'country_code' => 'EC', 'zone_name' => 'America/Guayaquil', 'del_status' => 'Live'],
            ['id' => 143, 'country_code' => 'EC', 'zone_name' => 'Pacific/Galapagos', 'del_status' => 'Live'],
            ['id' => 144, 'country_code' => 'EE', 'zone_name' => 'Europe/Tallinn', 'del_status' => 'Live'],
            ['id' => 145, 'country_code' => 'EG', 'zone_name' => 'Africa/Cairo', 'del_status' => 'Live'],
            ['id' => 146, 'country_code' => 'EH', 'zone_name' => 'Africa/El_Aaiun', 'del_status' => 'Live'],
            ['id' => 147, 'country_code' => 'ER', 'zone_name' => 'Africa/Asmara', 'del_status' => 'Live'],
            ['id' => 148, 'country_code' => 'ES', 'zone_name' => 'Europe/Madrid', 'del_status' => 'Live'],
            ['id' => 149, 'country_code' => 'ES', 'zone_name' => 'Africa/Ceuta', 'del_status' => 'Live'],
            ['id' => 150, 'country_code' => 'ES', 'zone_name' => 'Atlantic/Canary', 'del_status' => 'Live'],
            ['id' => 151, 'country_code' => 'ET', 'zone_name' => 'Africa/Addis_Ababa', 'del_status' => 'Live'],
            ['id' => 152, 'country_code' => 'FI', 'zone_name' => 'Europe/Helsinki', 'del_status' => 'Live'],
            ['id' => 153, 'country_code' => 'FJ', 'zone_name' => 'Pacific/Fiji', 'del_status' => 'Live'],
            ['id' => 154, 'country_code' => 'FK', 'zone_name' => 'Atlantic/Stanley', 'del_status' => 'Live'],
            ['id' => 155, 'country_code' => 'FM', 'zone_name' => 'Pacific/Chuuk', 'del_status' => 'Live'],
            ['id' => 156, 'country_code' => 'FM', 'zone_name' => 'Pacific/Pohnpei', 'del_status' => 'Live'],
            ['id' => 157, 'country_code' => 'FM', 'zone_name' => 'Pacific/Kosrae', 'del_status' => 'Live'],
            ['id' => 158, 'country_code' => 'FO', 'zone_name' => 'Atlantic/Faroe', 'del_status' => 'Live'],
            ['id' => 159, 'country_code' => 'FR', 'zone_name' => 'Europe/Paris', 'del_status' => 'Live'],
            ['id' => 160, 'country_code' => 'GA', 'zone_name' => 'Africa/Libreville', 'del_status' => 'Live'],
            ['id' => 161, 'country_code' => 'GB', 'zone_name' => 'Europe/London', 'del_status' => 'Live'],
            ['id' => 162, 'country_code' => 'GD', 'zone_name' => 'America/Grenada', 'del_status' => 'Live'],
            ['id' => 163, 'country_code' => 'GE', 'zone_name' => 'Asia/Tbilisi', 'del_status' => 'Live'],
            ['id' => 164, 'country_code' => 'GF', 'zone_name' => 'America/Cayenne', 'del_status' => 'Live'],
            ['id' => 165, 'country_code' => 'GG', 'zone_name' => 'Europe/Guernsey', 'del_status' => 'Live'],
            ['id' => 166, 'country_code' => 'GH', 'zone_name' => 'Africa/Accra', 'del_status' => 'Live'],
            ['id' => 167, 'country_code' => 'GI', 'zone_name' => 'Europe/Gibraltar', 'del_status' => 'Live'],
            ['id' => 168, 'country_code' => 'GL', 'zone_name' => 'America/Godthab', 'del_status' => 'Live'],
            ['id' => 169, 'country_code' => 'GL', 'zone_name' => 'America/Danmarkshavn', 'del_status' => 'Live'],
            ['id' => 170, 'country_code' => 'GL', 'zone_name' => 'America/Scoresbysund', 'del_status' => 'Live'],
            ['id' => 171, 'country_code' => 'GL', 'zone_name' => 'America/Thule', 'del_status' => 'Live'],
            ['id' => 172, 'country_code' => 'GM', 'zone_name' => 'Africa/Banjul', 'del_status' => 'Live'],
            ['id' => 173, 'country_code' => 'GN', 'zone_name' => 'Africa/Conakry', 'del_status' => 'Live'],
            ['id' => 174, 'country_code' => 'GP', 'zone_name' => 'America/Guadeloupe', 'del_status' => 'Live'],
            ['id' => 175, 'country_code' => 'GQ', 'zone_name' => 'Africa/Malabo', 'del_status' => 'Live'],
            ['id' => 176, 'country_code' => 'GR', 'zone_name' => 'Europe/Athens', 'del_status' => 'Live'],
            ['id' => 177, 'country_code' => 'GS', 'zone_name' => 'Atlantic/South_Georgia', 'del_status' => 'Live'],
            ['id' => 178, 'country_code' => 'GT', 'zone_name' => 'America/Guatemala', 'del_status' => 'Live'],
            ['id' => 179, 'country_code' => 'GU', 'zone_name' => 'Pacific/Guam', 'del_status' => 'Live'],
            ['id' => 180, 'country_code' => 'GW', 'zone_name' => 'Africa/Bissau', 'del_status' => 'Live'],
            ['id' => 181, 'country_code' => 'GY', 'zone_name' => 'America/Guyana', 'del_status' => 'Live'],
            ['id' => 182, 'country_code' => 'HK', 'zone_name' => 'Asia/Hong_Kong', 'del_status' => 'Live'],
            ['id' => 183, 'country_code' => 'HN', 'zone_name' => 'America/Tegucigalpa', 'del_status' => 'Live'],
            ['id' => 184, 'country_code' => 'HR', 'zone_name' => 'Europe/Zagreb', 'del_status' => 'Live'],
            ['id' => 185, 'country_code' => 'HT', 'zone_name' => 'America/Port-au-Prince', 'del_status' => 'Live'],
            ['id' => 186, 'country_code' => 'HU', 'zone_name' => 'Europe/Budapest', 'del_status' => 'Live'],
            ['id' => 187, 'country_code' => 'ID', 'zone_name' => 'Asia/Jakarta', 'del_status' => 'Live'],
            ['id' => 188, 'country_code' => 'ID', 'zone_name' => 'Asia/Pontianak', 'del_status' => 'Live'],
            ['id' => 189, 'country_code' => 'ID', 'zone_name' => 'Asia/Makassar', 'del_status' => 'Live'],
            ['id' => 190, 'country_code' => 'ID', 'zone_name' => 'Asia/Jayapura', 'del_status' => 'Live'],
            ['id' => 191, 'country_code' => 'IE', 'zone_name' => 'Europe/Dublin', 'del_status' => 'Live'],
            ['id' => 192, 'country_code' => 'IL', 'zone_name' => 'Asia/Jerusalem', 'del_status' => 'Live'],
            ['id' => 193, 'country_code' => 'IM', 'zone_name' => 'Europe/Isle_of_Man', 'del_status' => 'Live'],
            ['id' => 194, 'country_code' => 'IN', 'zone_name' => 'Asia/Kolkata', 'del_status' => 'Live'],
            ['id' => 195, 'country_code' => 'IO', 'zone_name' => 'Indian/Chagos', 'del_status' => 'Live'],
            ['id' => 196, 'country_code' => 'IQ', 'zone_name' => 'Asia/Baghdad', 'del_status' => 'Live'],
            ['id' => 197, 'country_code' => 'IR', 'zone_name' => 'Asia/Tehran', 'del_status' => 'Live'],
            ['id' => 198, 'country_code' => 'IS', 'zone_name' => 'Atlantic/Reykjavik', 'del_status' => 'Live'],
            ['id' => 199, 'country_code' => 'IT', 'zone_name' => 'Europe/Rome', 'del_status' => 'Live'],
            ['id' => 200, 'country_code' => 'JE', 'zone_name' => 'Europe/Jersey', 'del_status' => 'Live'],
            ['id' => 201, 'country_code' => 'JM', 'zone_name' => 'America/Jamaica', 'del_status' => 'Live'],
            ['id' => 202, 'country_code' => 'JO', 'zone_name' => 'Asia/Amman', 'del_status' => 'Live'],
            ['id' => 203, 'country_code' => 'JP', 'zone_name' => 'Asia/Tokyo', 'del_status' => 'Live'],
            ['id' => 204, 'country_code' => 'KE', 'zone_name' => 'Africa/Nairobi', 'del_status' => 'Live'],
            ['id' => 205, 'country_code' => 'KG', 'zone_name' => 'Asia/Bishkek', 'del_status' => 'Live'],
            ['id' => 206, 'country_code' => 'KH', 'zone_name' => 'Asia/Phnom_Penh', 'del_status' => 'Live'],
            ['id' => 207, 'country_code' => 'KI', 'zone_name' => 'Pacific/Tarawa', 'del_status' => 'Live'],
            ['id' => 208, 'country_code' => 'KI', 'zone_name' => 'Pacific/Enderbury', 'del_status' => 'Live'],
            ['id' => 209, 'country_code' => 'KI', 'zone_name' => 'Pacific/Kiritimati', 'del_status' => 'Live'],
            ['id' => 210, 'country_code' => 'KM', 'zone_name' => 'Indian/Comoro', 'del_status' => 'Live'],
            ['id' => 211, 'country_code' => 'KN', 'zone_name' => 'America/St_Kitts', 'del_status' => 'Live'],
            ['id' => 212, 'country_code' => 'KP', 'zone_name' => 'Asia/Pyongyang', 'del_status' => 'Live'],
            ['id' => 213, 'country_code' => 'KR', 'zone_name' => 'Asia/Seoul', 'del_status' => 'Live'],
            ['id' => 214, 'country_code' => 'KW', 'zone_name' => 'Asia/Kuwait', 'del_status' => 'Live'],
            ['id' => 215, 'country_code' => 'KY', 'zone_name' => 'America/Cayman', 'del_status' => 'Live'],
            ['id' => 216, 'country_code' => 'KZ', 'zone_name' => 'Asia/Almaty', 'del_status' => 'Live'],
            ['id' => 217, 'country_code' => 'KZ', 'zone_name' => 'Asia/Qyzylorda', 'del_status' => 'Live'],
            ['id' => 218, 'country_code' => 'KZ', 'zone_name' => 'Asia/Aqtobe', 'del_status' => 'Live'],
            ['id' => 219, 'country_code' => 'KZ', 'zone_name' => 'Asia/Aqtau', 'del_status' => 'Live'],
            ['id' => 220, 'country_code' => 'KZ', 'zone_name' => 'Asia/Atyrau', 'del_status' => 'Live'],
            ['id' => 221, 'country_code' => 'KZ', 'zone_name' => 'Asia/Oral', 'del_status' => 'Live'],
            ['id' => 222, 'country_code' => 'LA', 'zone_name' => 'Asia/Vientiane', 'del_status' => 'Live'],
            ['id' => 223, 'country_code' => 'LB', 'zone_name' => 'Asia/Beirut', 'del_status' => 'Live'],
            ['id' => 224, 'country_code' => 'LC', 'zone_name' => 'America/St_Lucia', 'del_status' => 'Live'],
            ['id' => 225, 'country_code' => 'LI', 'zone_name' => 'Europe/Vaduz', 'del_status' => 'Live'],
            ['id' => 226, 'country_code' => 'LK', 'zone_name' => 'Asia/Colombo', 'del_status' => 'Live'],
            ['id' => 227, 'country_code' => 'LR', 'zone_name' => 'Africa/Monrovia', 'del_status' => 'Live'],
            ['id' => 228, 'country_code' => 'LS', 'zone_name' => 'Africa/Maseru', 'del_status' => 'Live'],
            ['id' => 229, 'country_code' => 'LT', 'zone_name' => 'Europe/Vilnius', 'del_status' => 'Live'],
            ['id' => 230, 'country_code' => 'LU', 'zone_name' => 'Europe/Luxembourg', 'del_status' => 'Live'],
            ['id' => 231, 'country_code' => 'LV', 'zone_name' => 'Europe/Riga', 'del_status' => 'Live'],
            ['id' => 232, 'country_code' => 'LY', 'zone_name' => 'Africa/Tripoli', 'del_status' => 'Live'],
            ['id' => 233, 'country_code' => 'MA', 'zone_name' => 'Africa/Casablanca', 'del_status' => 'Live'],
            ['id' => 234, 'country_code' => 'MC', 'zone_name' => 'Europe/Monaco', 'del_status' => 'Live'],
            ['id' => 235, 'country_code' => 'MD', 'zone_name' => 'Europe/Chisinau', 'del_status' => 'Live'],
            ['id' => 236, 'country_code' => 'ME', 'zone_name' => 'Europe/Podgorica', 'del_status' => 'Live'],
            ['id' => 237, 'country_code' => 'MF', 'zone_name' => 'America/Marigot', 'del_status' => 'Live'],
            ['id' => 238, 'country_code' => 'MG', 'zone_name' => 'Indian/Antananarivo', 'del_status' => 'Live'],
            ['id' => 239, 'country_code' => 'MH', 'zone_name' => 'Pacific/Majuro', 'del_status' => 'Live'],
            ['id' => 240, 'country_code' => 'MH', 'zone_name' => 'Pacific/Kwajalein', 'del_status' => 'Live'],
            ['id' => 241, 'country_code' => 'MK', 'zone_name' => 'Europe/Skopje', 'del_status' => 'Live'],
            ['id' => 242, 'country_code' => 'ML', 'zone_name' => 'Africa/Bamako', 'del_status' => 'Live'],
            ['id' => 243, 'country_code' => 'MM', 'zone_name' => 'Asia/Yangon', 'del_status' => 'Live'],
            ['id' => 244, 'country_code' => 'MN', 'zone_name' => 'Asia/Ulaanbaatar', 'del_status' => 'Live'],
            ['id' => 245, 'country_code' => 'MN', 'zone_name' => 'Asia/Hovd', 'del_status' => 'Live'],
            ['id' => 246, 'country_code' => 'MN', 'zone_name' => 'Asia/Choibalsan', 'del_status' => 'Live'],
            ['id' => 247, 'country_code' => 'MO', 'zone_name' => 'Asia/Macau', 'del_status' => 'Live'],
            ['id' => 248, 'country_code' => 'MP', 'zone_name' => 'Pacific/Saipan', 'del_status' => 'Live'],
            ['id' => 249, 'country_code' => 'MQ', 'zone_name' => 'America/Martinique', 'del_status' => 'Live'],
            ['id' => 250, 'country_code' => 'MR', 'zone_name' => 'Africa/Nouakchott', 'del_status' => 'Live'],
            ['id' => 251, 'country_code' => 'MS', 'zone_name' => 'America/Montserrat', 'del_status' => 'Live'],
            ['id' => 252, 'country_code' => 'MT', 'zone_name' => 'Europe/Malta', 'del_status' => 'Live'],
            ['id' => 253, 'country_code' => 'MU', 'zone_name' => 'Indian/Mauritius', 'del_status' => 'Live'],
            ['id' => 254, 'country_code' => 'MV', 'zone_name' => 'Indian/Maldives', 'del_status' => 'Live'],
            ['id' => 255, 'country_code' => 'MW', 'zone_name' => 'Africa/Blantyre', 'del_status' => 'Live'],
            ['id' => 256, 'country_code' => 'MX', 'zone_name' => 'America/Mexico_City', 'del_status' => 'Live'],
            ['id' => 257, 'country_code' => 'MX', 'zone_name' => 'America/Cancun', 'del_status' => 'Live'],
            ['id' => 258, 'country_code' => 'MX', 'zone_name' => 'America/Merida', 'del_status' => 'Live'],
            ['id' => 259, 'country_code' => 'MX', 'zone_name' => 'America/Monterrey', 'del_status' => 'Live'],
            ['id' => 260, 'country_code' => 'MX', 'zone_name' => 'America/Matamoros', 'del_status' => 'Live'],
            ['id' => 261, 'country_code' => 'MX', 'zone_name' => 'America/Mazatlan', 'del_status' => 'Live'],
            ['id' => 262, 'country_code' => 'MX', 'zone_name' => 'America/Chihuahua', 'del_status' => 'Live'],
            ['id' => 263, 'country_code' => 'MX', 'zone_name' => 'America/Ojinaga', 'del_status' => 'Live'],
            ['id' => 264, 'country_code' => 'MX', 'zone_name' => 'America/Hermosillo', 'del_status' => 'Live'],
            ['id' => 265, 'country_code' => 'MX', 'zone_name' => 'America/Tijuana', 'del_status' => 'Live'],
            ['id' => 266, 'country_code' => 'MX', 'zone_name' => 'America/Bahia_Banderas', 'del_status' => 'Live'],
            ['id' => 267, 'country_code' => 'MY', 'zone_name' => 'Asia/Kuala_Lumpur', 'del_status' => 'Live'],
            ['id' => 268, 'country_code' => 'MY', 'zone_name' => 'Asia/Kuching', 'del_status' => 'Live'],
            ['id' => 269, 'country_code' => 'MZ', 'zone_name' => 'Africa/Maputo', 'del_status' => 'Live'],
            ['id' => 270, 'country_code' => 'NA', 'zone_name' => 'Africa/Windhoek', 'del_status' => 'Live'],
            ['id' => 271, 'country_code' => 'NC', 'zone_name' => 'Pacific/Noumea', 'del_status' => 'Live'],
            ['id' => 272, 'country_code' => 'NE', 'zone_name' => 'Africa/Niamey', 'del_status' => 'Live'],
            ['id' => 273, 'country_code' => 'NF', 'zone_name' => 'Pacific/Norfolk', 'del_status' => 'Live'],
            ['id' => 274, 'country_code' => 'NG', 'zone_name' => 'Africa/Lagos', 'del_status' => 'Live'],
            ['id' => 275, 'country_code' => 'NI', 'zone_name' => 'America/Managua', 'del_status' => 'Live'],
            ['id' => 276, 'country_code' => 'NL', 'zone_name' => 'Europe/Amsterdam', 'del_status' => 'Live'],
            ['id' => 277, 'country_code' => 'NO', 'zone_name' => 'Europe/Oslo', 'del_status' => 'Live'],
            ['id' => 278, 'country_code' => 'NP', 'zone_name' => 'Asia/Kathmandu', 'del_status' => 'Live'],
            ['id' => 279, 'country_code' => 'NR', 'zone_name' => 'Pacific/Nauru', 'del_status' => 'Live'],
            ['id' => 280, 'country_code' => 'NU', 'zone_name' => 'Pacific/Niue', 'del_status' => 'Live'],
            ['id' => 281, 'country_code' => 'NZ', 'zone_name' => 'Pacific/Auckland', 'del_status' => 'Live'],
            ['id' => 282, 'country_code' => 'NZ', 'zone_name' => 'Pacific/Chatham', 'del_status' => 'Live'],
            ['id' => 283, 'country_code' => 'OM', 'zone_name' => 'Asia/Muscat', 'del_status' => 'Live'],
            ['id' => 284, 'country_code' => 'PA', 'zone_name' => 'America/Panama', 'del_status' => 'Live'],
            ['id' => 285, 'country_code' => 'PE', 'zone_name' => 'America/Lima', 'del_status' => 'Live'],
            ['id' => 286, 'country_code' => 'PF', 'zone_name' => 'Pacific/Tahiti', 'del_status' => 'Live'],
            ['id' => 287, 'country_code' => 'PF', 'zone_name' => 'Pacific/Marquesas', 'del_status' => 'Live'],
            ['id' => 288, 'country_code' => 'PF', 'zone_name' => 'Pacific/Gambier', 'del_status' => 'Live'],
            ['id' => 289, 'country_code' => 'PG', 'zone_name' => 'Pacific/Port_Moresby', 'del_status' => 'Live'],
            ['id' => 290, 'country_code' => 'PG', 'zone_name' => 'Pacific/Bougainville', 'del_status' => 'Live'],
            ['id' => 291, 'country_code' => 'PH', 'zone_name' => 'Asia/Manila', 'del_status' => 'Live'],
            ['id' => 292, 'country_code' => 'PK', 'zone_name' => 'Asia/Karachi', 'del_status' => 'Live'],
            ['id' => 293, 'country_code' => 'PL', 'zone_name' => 'Europe/Warsaw', 'del_status' => 'Live'],
            ['id' => 294, 'country_code' => 'PM', 'zone_name' => 'America/Miquelon', 'del_status' => 'Live'],
            ['id' => 295, 'country_code' => 'PN', 'zone_name' => 'Pacific/Pitcairn', 'del_status' => 'Live'],
            ['id' => 296, 'country_code' => 'PR', 'zone_name' => 'America/Puerto_Rico', 'del_status' => 'Live'],
            ['id' => 297, 'country_code' => 'PS', 'zone_name' => 'Asia/Gaza', 'del_status' => 'Live'],
            ['id' => 298, 'country_code' => 'PS', 'zone_name' => 'Asia/Hebron', 'del_status' => 'Live'],
            ['id' => 299, 'country_code' => 'PT', 'zone_name' => 'Europe/Lisbon', 'del_status' => 'Live'],
            ['id' => 300, 'country_code' => 'PT', 'zone_name' => 'Atlantic/Madeira', 'del_status' => 'Live'],
            ['id' => 301, 'country_code' => 'PT', 'zone_name' => 'Atlantic/Azores', 'del_status' => 'Live'],
            ['id' => 302, 'country_code' => 'PW', 'zone_name' => 'Pacific/Palau', 'del_status' => 'Live'],
            ['id' => 303, 'country_code' => 'PY', 'zone_name' => 'America/Asuncion', 'del_status' => 'Live'],
            ['id' => 304, 'country_code' => 'QA', 'zone_name' => 'Asia/Qatar', 'del_status' => 'Live'],
            ['id' => 305, 'country_code' => 'RE', 'zone_name' => 'Indian/Reunion', 'del_status' => 'Live'],
            ['id' => 306, 'country_code' => 'RO', 'zone_name' => 'Europe/Bucharest', 'del_status' => 'Live'],
            ['id' => 307, 'country_code' => 'RS', 'zone_name' => 'Europe/Belgrade', 'del_status' => 'Live'],
            ['id' => 308, 'country_code' => 'RU', 'zone_name' => 'Europe/Kaliningrad', 'del_status' => 'Live'],
            ['id' => 309, 'country_code' => 'RU', 'zone_name' => 'Europe/Moscow', 'del_status' => 'Live'],
            ['id' => 310, 'country_code' => 'RU', 'zone_name' => 'Europe/Simferopol', 'del_status' => 'Live'],
            ['id' => 311, 'country_code' => 'RU', 'zone_name' => 'Europe/Volgograd', 'del_status' => 'Live'],
            ['id' => 312, 'country_code' => 'RU', 'zone_name' => 'Europe/Kirov', 'del_status' => 'Live'],
            ['id' => 313, 'country_code' => 'RU', 'zone_name' => 'Europe/Astrakhan', 'del_status' => 'Live'],
            ['id' => 314, 'country_code' => 'RU', 'zone_name' => 'Europe/Saratov', 'del_status' => 'Live'],
            ['id' => 315, 'country_code' => 'RU', 'zone_name' => 'Europe/Ulyanovsk', 'del_status' => 'Live'],
            ['id' => 316, 'country_code' => 'RU', 'zone_name' => 'Europe/Samara', 'del_status' => 'Live'],
            ['id' => 317, 'country_code' => 'RU', 'zone_name' => 'Asia/Yekaterinburg', 'del_status' => 'Live'],
            ['id' => 318, 'country_code' => 'RU', 'zone_name' => 'Asia/Omsk', 'del_status' => 'Live'],
            ['id' => 319, 'country_code' => 'RU', 'zone_name' => 'Asia/Novosibirsk', 'del_status' => 'Live'],
            ['id' => 320, 'country_code' => 'RU', 'zone_name' => 'Asia/Barnaul', 'del_status' => 'Live'],
            ['id' => 321, 'country_code' => 'RU', 'zone_name' => 'Asia/Tomsk', 'del_status' => 'Live'],
            ['id' => 322, 'country_code' => 'RU', 'zone_name' => 'Asia/Novokuznetsk', 'del_status' => 'Live'],
            ['id' => 323, 'country_code' => 'RU', 'zone_name' => 'Asia/Krasnoyarsk', 'del_status' => 'Live'],
            ['id' => 324, 'country_code' => 'RU', 'zone_name' => 'Asia/Irkutsk', 'del_status' => 'Live'],
            ['id' => 325, 'country_code' => 'RU', 'zone_name' => 'Asia/Chita', 'del_status' => 'Live'],
            ['id' => 326, 'country_code' => 'RU', 'zone_name' => 'Asia/Yakutsk', 'del_status' => 'Live'],
            ['id' => 327, 'country_code' => 'RU', 'zone_name' => 'Asia/Khandyga', 'del_status' => 'Live'],
            ['id' => 328, 'country_code' => 'RU', 'zone_name' => 'Asia/Vladivostok', 'del_status' => 'Live'],
            ['id' => 329, 'country_code' => 'RU', 'zone_name' => 'Asia/Ust-Nera', 'del_status' => 'Live'],
            ['id' => 330, 'country_code' => 'RU', 'zone_name' => 'Asia/Magadan', 'del_status' => 'Live'],
            ['id' => 331, 'country_code' => 'RU', 'zone_name' => 'Asia/Sakhalin', 'del_status' => 'Live'],
            ['id' => 332, 'country_code' => 'RU', 'zone_name' => 'Asia/Srednekolymsk', 'del_status' => 'Live'],
            ['id' => 333, 'country_code' => 'RU', 'zone_name' => 'Asia/Kamchatka', 'del_status' => 'Live'],
            ['id' => 334, 'country_code' => 'RU', 'zone_name' => 'Asia/Anadyr', 'del_status' => 'Live'],
            ['id' => 335, 'country_code' => 'RW', 'zone_name' => 'Africa/Kigali', 'del_status' => 'Live'],
            ['id' => 336, 'country_code' => 'SA', 'zone_name' => 'Asia/Riyadh', 'del_status' => 'Live'],
            ['id' => 337, 'country_code' => 'SB', 'zone_name' => 'Pacific/Guadalcanal', 'del_status' => 'Live'],
            ['id' => 338, 'country_code' => 'SC', 'zone_name' => 'Indian/Mahe', 'del_status' => 'Live'],
            ['id' => 339, 'country_code' => 'SD', 'zone_name' => 'Africa/Khartoum', 'del_status' => 'Live'],
            ['id' => 340, 'country_code' => 'SE', 'zone_name' => 'Europe/Stockholm', 'del_status' => 'Live'],
            ['id' => 341, 'country_code' => 'SG', 'zone_name' => 'Asia/Singapore', 'del_status' => 'Live'],
            ['id' => 342, 'country_code' => 'SH', 'zone_name' => 'Atlantic/St_Helena', 'del_status' => 'Live'],
            ['id' => 343, 'country_code' => 'SI', 'zone_name' => 'Europe/Ljubljana', 'del_status' => 'Live'],
            ['id' => 344, 'country_code' => 'SJ', 'zone_name' => 'Arctic/Longyearbyen', 'del_status' => 'Live'],
            ['id' => 345, 'country_code' => 'SK', 'zone_name' => 'Europe/Bratislava', 'del_status' => 'Live'],
            ['id' => 346, 'country_code' => 'SL', 'zone_name' => 'Africa/Freetown', 'del_status' => 'Live'],
            ['id' => 347, 'country_code' => 'SM', 'zone_name' => 'Europe/San_Marino', 'del_status' => 'Live'],
            ['id' => 348, 'country_code' => 'SN', 'zone_name' => 'Africa/Dakar', 'del_status' => 'Live'],
            ['id' => 349, 'country_code' => 'SO', 'zone_name' => 'Africa/Mogadishu', 'del_status' => 'Live'],
            ['id' => 350, 'country_code' => 'SR', 'zone_name' => 'America/Paramaribo', 'del_status' => 'Live'],
            ['id' => 351, 'country_code' => 'SS', 'zone_name' => 'Africa/Juba', 'del_status' => 'Live'],
            ['id' => 352, 'country_code' => 'ST', 'zone_name' => 'Africa/Sao_Tome', 'del_status' => 'Live'],
            ['id' => 353, 'country_code' => 'SV', 'zone_name' => 'America/El_Salvador', 'del_status' => 'Live'],
            ['id' => 354, 'country_code' => 'SX', 'zone_name' => 'America/Lower_Princes', 'del_status' => 'Live'],
            ['id' => 355, 'country_code' => 'SY', 'zone_name' => 'Asia/Damascus', 'del_status' => 'Live'],
            ['id' => 356, 'country_code' => 'SZ', 'zone_name' => 'Africa/Mbabane', 'del_status' => 'Live'],
            ['id' => 357, 'country_code' => 'TC', 'zone_name' => 'America/Grand_Turk', 'del_status' => 'Live'],
            ['id' => 358, 'country_code' => 'TD', 'zone_name' => 'Africa/Ndjamena', 'del_status' => 'Live'],
            ['id' => 359, 'country_code' => 'TF', 'zone_name' => 'Indian/Kerguelen', 'del_status' => 'Live'],
            ['id' => 360, 'country_code' => 'TG', 'zone_name' => 'Africa/Lome', 'del_status' => 'Live'],
            ['id' => 361, 'country_code' => 'TH', 'zone_name' => 'Asia/Bangkok', 'del_status' => 'Live'],
            ['id' => 362, 'country_code' => 'TJ', 'zone_name' => 'Asia/Dushanbe', 'del_status' => 'Live'],
            ['id' => 363, 'country_code' => 'TK', 'zone_name' => 'Pacific/Fakaofo', 'del_status' => 'Live'],
            ['id' => 364, 'country_code' => 'TL', 'zone_name' => 'Asia/Dili', 'del_status' => 'Live'],
            ['id' => 365, 'country_code' => 'TM', 'zone_name' => 'Asia/Ashgabat', 'del_status' => 'Live'],
            ['id' => 366, 'country_code' => 'TN', 'zone_name' => 'Africa/Tunis', 'del_status' => 'Live'],
            ['id' => 367, 'country_code' => 'TO', 'zone_name' => 'Pacific/Tongatapu', 'del_status' => 'Live'],
            ['id' => 368, 'country_code' => 'TR', 'zone_name' => 'Europe/Istanbul', 'del_status' => 'Live'],
            ['id' => 369, 'country_code' => 'TT', 'zone_name' => 'America/Port_of_Spain', 'del_status' => 'Live'],
            ['id' => 370, 'country_code' => 'TV', 'zone_name' => 'Pacific/Funafuti', 'del_status' => 'Live'],
            ['id' => 371, 'country_code' => 'TW', 'zone_name' => 'Asia/Taipei', 'del_status' => 'Live'],
            ['id' => 372, 'country_code' => 'TZ', 'zone_name' => 'Africa/Dar_es_Salaam', 'del_status' => 'Live'],
            ['id' => 373, 'country_code' => 'UA', 'zone_name' => 'Europe/Kiev', 'del_status' => 'Live'],
            ['id' => 374, 'country_code' => 'UA', 'zone_name' => 'Europe/Uzhgorod', 'del_status' => 'Live'],
            ['id' => 375, 'country_code' => 'UA', 'zone_name' => 'Europe/Zaporozhye', 'del_status' => 'Live'],
            ['id' => 376, 'country_code' => 'UG', 'zone_name' => 'Africa/Kampala', 'del_status' => 'Live'],
            ['id' => 377, 'country_code' => 'UM', 'zone_name' => 'Pacific/Midway', 'del_status' => 'Live'],
            ['id' => 378, 'country_code' => 'UM', 'zone_name' => 'Pacific/Wake', 'del_status' => 'Live'],
            ['id' => 379, 'country_code' => 'US', 'zone_name' => 'America/New_York', 'del_status' => 'Live'],
            ['id' => 380, 'country_code' => 'US', 'zone_name' => 'America/Detroit', 'del_status' => 'Live'],
            ['id' => 381, 'country_code' => 'US', 'zone_name' => 'America/Kentucky/Louisville', 'del_status' => 'Live'],
            ['id' => 382, 'country_code' => 'US', 'zone_name' => 'America/Kentucky/Monticello', 'del_status' => 'Live'],
            ['id' => 383, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Indianapolis', 'del_status' => 'Live'],
            ['id' => 384, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Vincennes', 'del_status' => 'Live'],
            ['id' => 385, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Winamac', 'del_status' => 'Live'],
            ['id' => 386, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Marengo', 'del_status' => 'Live'],
            ['id' => 387, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Petersburg', 'del_status' => 'Live'],
            ['id' => 388, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Vevay', 'del_status' => 'Live'],
            ['id' => 389, 'country_code' => 'US', 'zone_name' => 'America/Chicago', 'del_status' => 'Live'],
            ['id' => 390, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Tell_City', 'del_status' => 'Live'],
            ['id' => 391, 'country_code' => 'US', 'zone_name' => 'America/Indiana/Knox', 'del_status' => 'Live'],
            ['id' => 392, 'country_code' => 'US', 'zone_name' => 'America/Menominee', 'del_status' => 'Live'],
            ['id' => 393, 'country_code' => 'US', 'zone_name' => 'America/North_Dakota/Center', 'del_status' => 'Live'],
            ['id' => 394, 'country_code' => 'US', 'zone_name' => 'America/North_Dakota/New_Salem', 'del_status' => 'Live'],
            ['id' => 395, 'country_code' => 'US', 'zone_name' => 'America/North_Dakota/Beulah', 'del_status' => 'Live'],
            ['id' => 396, 'country_code' => 'US', 'zone_name' => 'America/Denver', 'del_status' => 'Live'],
            ['id' => 397, 'country_code' => 'US', 'zone_name' => 'America/Boise', 'del_status' => 'Live'],
            ['id' => 398, 'country_code' => 'US', 'zone_name' => 'America/Phoenix', 'del_status' => 'Live'],
            ['id' => 399, 'country_code' => 'US', 'zone_name' => 'America/Los_Angeles', 'del_status' => 'Live'],
            ['id' => 400, 'country_code' => 'US', 'zone_name' => 'America/Anchorage', 'del_status' => 'Live'],
            ['id' => 401, 'country_code' => 'US', 'zone_name' => 'America/Juneau', 'del_status' => 'Live'],
            ['id' => 402, 'country_code' => 'US', 'zone_name' => 'America/Sitka', 'del_status' => 'Live'],
            ['id' => 403, 'country_code' => 'US', 'zone_name' => 'America/Metlakatla', 'del_status' => 'Live'],
            ['id' => 404, 'country_code' => 'US', 'zone_name' => 'America/Yakutat', 'del_status' => 'Live'],
            ['id' => 405, 'country_code' => 'US', 'zone_name' => 'America/Nome', 'del_status' => 'Live'],
            ['id' => 406, 'country_code' => 'US', 'zone_name' => 'America/Adak', 'del_status' => 'Live'],
            ['id' => 407, 'country_code' => 'US', 'zone_name' => 'Pacific/Honolulu', 'del_status' => 'Live'],
            ['id' => 408, 'country_code' => 'UY', 'zone_name' => 'America/Montevideo', 'del_status' => 'Live'],
            ['id' => 409, 'country_code' => 'UZ', 'zone_name' => 'Asia/Samarkand', 'del_status' => 'Live'],
            ['id' => 410, 'country_code' => 'UZ', 'zone_name' => 'Asia/Tashkent', 'del_status' => 'Live'],
            ['id' => 411, 'country_code' => 'VA', 'zone_name' => 'Europe/Vatican', 'del_status' => 'Live'],
            ['id' => 412, 'country_code' => 'VC', 'zone_name' => 'America/St_Vincent', 'del_status' => 'Live'],
            ['id' => 413, 'country_code' => 'VE', 'zone_name' => 'America/Caracas', 'del_status' => 'Live'],
            ['id' => 414, 'country_code' => 'VG', 'zone_name' => 'America/Tortola', 'del_status' => 'Live'],
            ['id' => 415, 'country_code' => 'VI', 'zone_name' => 'America/St_Thomas', 'del_status' => 'Live'],
            ['id' => 416, 'country_code' => 'VN', 'zone_name' => 'Asia/Ho_Chi_Minh', 'del_status' => 'Live'],
            ['id' => 417, 'country_code' => 'VU', 'zone_name' => 'Pacific/Efate', 'del_status' => 'Live'],
            ['id' => 418, 'country_code' => 'WF', 'zone_name' => 'Pacific/Wallis', 'del_status' => 'Live'],
            ['id' => 419, 'country_code' => 'WS', 'zone_name' => 'Pacific/Apia', 'del_status' => 'Live'],
            ['id' => 420, 'country_code' => 'YE', 'zone_name' => 'Asia/Aden', 'del_status' => 'Live'],
            ['id' => 421, 'country_code' => 'YT', 'zone_name' => 'Indian/Mayotte', 'del_status' => 'Live'],
            ['id' => 422, 'country_code' => 'ZA', 'zone_name' => 'Africa/Johannesburg', 'del_status' => 'Live'],
            ['id' => 423, 'country_code' => 'ZM', 'zone_name' => 'Africa/Lusaka', 'del_status' => 'Live'],
            ['id' => 424, 'country_code' => 'ZW', 'zone_name' => 'Africa/Harare', 'del_status' => 'Live']
        ]);
        


        // foreach(range(1,1000) as $index) {
        //     User::create([
        //         'name' => fake()->name(),
        //         'role' => fake()->numberBetween(1, 3), // Assuming roles are between 1-3
        //         'email' => fake()->unique()->safeEmail(),
        //         'password' => bcrypt('password'), // Default password for all users
        //         'email_verified_at' => now(),
        //     ]);
        // }
        

    }
}
