CREATE TABLE IF NOT EXISTS `fixed_asset_stock_ins` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `reference_no` VARCHAR(255) DEFAULT NULL,
    `date` DATE DEFAULT NULL,
    `grand_total` DECIMAL(15,3) DEFAULT 0.000,
    `note` TEXT DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fixed_asset_stock_in_details` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `asset_stock_in_id` BIGINT UNSIGNED DEFAULT NULL,
    `item_id` BIGINT UNSIGNED DEFAULT NULL,
    `unit_price` DECIMAL(15,3) DEFAULT 0.000,
    `total` DECIMAL(15,3) DEFAULT 0.000,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`asset_stock_in_id`) REFERENCES `fixed_asset_stock_ins`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`item_id`) REFERENCES `fixed_asset_items`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fixed_asset_stock_outs` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `reference_no` VARCHAR(255) DEFAULT NULL,
    `date` DATE DEFAULT NULL,
    `grand_total` DECIMAL(15,3) DEFAULT 0.000,
    `note` TEXT DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `fixed_asset_stock_out_details` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `asset_stock_out_id` BIGINT UNSIGNED DEFAULT NULL,
    `item_id` BIGINT UNSIGNED DEFAULT NULL,
    `unit_price` DECIMAL(15,3) DEFAULT 0.000,
    `total` DECIMAL(15,3) DEFAULT 0.000,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`asset_stock_out_id`) REFERENCES `fixed_asset_stock_outs`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`item_id`) REFERENCES `fixed_asset_items`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customers` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) DEFAULT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `phone` VARCHAR(50) DEFAULT NULL,
    `address` TEXT DEFAULT NULL,
    `city` VARCHAR(255) DEFAULT NULL,
    `state_id` BIGINT UNSIGNED DEFAULT NULL,
    `postal_code` VARCHAR(20) DEFAULT NULL,
    `country` VARCHAR(100) DEFAULT NULL,
    `gst_number` VARCHAR(50) DEFAULT NULL,
    `opening_balance` DECIMAL(15,3) DEFAULT 0.000,
    `opening_balance_type` VARCHAR(20) DEFAULT NULL,
    `credit_limit` DECIMAL(15,3) DEFAULT 0.000,
    `description` TEXT DEFAULT NULL,
    `photo` VARCHAR(255) DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`state_id`) REFERENCES `states`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sales` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `invoice_no` VARCHAR(255) DEFAULT NULL,
    `sale_date` DATE DEFAULT NULL,
    `date_time` DATETIME DEFAULT NULL,
    `order_time` DATETIME DEFAULT NULL,
    `due_date` DATE DEFAULT NULL,
    `due_date_time` DATETIME DEFAULT NULL,
    `order_date_time` DATETIME DEFAULT NULL,
    `close_time` DATETIME DEFAULT NULL,
    `customer_id` BIGINT UNSIGNED DEFAULT NULL,
    `employee_id` BIGINT UNSIGNED DEFAULT NULL,
    `sub_total` DECIMAL(15,3) DEFAULT 0.000,
    `given_amount` DECIMAL(15,3) DEFAULT 0.000,
    `paid_amount` DECIMAL(15,3) DEFAULT 0.000,
    `change_amount` DECIMAL(15,3) DEFAULT 0.000,
    `previous_due` DECIMAL(15,3) DEFAULT 0.000,
    `due_amount` DECIMAL(15,3) DEFAULT 0.000,
    `disc` DECIMAL(15,3) DEFAULT 0.000,
    `disc_actual` DECIMAL(15,3) DEFAULT 0.000,
    `vat` DECIMAL(15,3) DEFAULT 0.000,
    `rounding` DECIMAL(15,3) DEFAULT 0.000,
    `total_payable` DECIMAL(15,3) DEFAULT 0.000,
    `total_item_discount_amount` DECIMAL(15,3) DEFAULT 0.000,
    `sub_total_with_discount` DECIMAL(15,3) DEFAULT 0.000,
    `sub_total_discount_amount` DECIMAL(15,3) DEFAULT 0.000,
    `total_discount_amount` DECIMAL(15,3) DEFAULT 0.000,
    `delivery_charge` DECIMAL(15,3) DEFAULT 0.000,
    `sub_total_discount_value` DECIMAL(15,3) DEFAULT 0.000,
    `grand_total` DECIMAL(15,3) DEFAULT 0.000,
    `sale_vat_objects` JSON DEFAULT NULL,
    `delivery_partner_id` BIGINT UNSIGNED DEFAULT NULL,
    `note` TEXT DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`employee_id`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`delivery_partner_id`) REFERENCES `delivery_partners`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_details` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `sales_id` BIGINT UNSIGNED DEFAULT NULL,
    `item_id` BIGINT UNSIGNED DEFAULT NULL,
    `qty` DECIMAL(15,3) DEFAULT 0.000,
    `menu_price_without_discount` DECIMAL(15,3) DEFAULT 0.000,
    `menu_price_with_discount` DECIMAL(15,3) DEFAULT 0.000,
    `menu_unit_price` DECIMAL(15,3) DEFAULT 0.000,
    `purchase_price` DECIMAL(15,3) DEFAULT 0.000,
    `menu_vat_percentage` DECIMAL(5,2) DEFAULT 0.00,
    `item_tax_amount` DECIMAL(15,3) DEFAULT 0.000,
    `menu_discount_value` DECIMAL(15,3) DEFAULT 0.000,
    `discount_amount` DECIMAL(15,3) DEFAULT 0.000,
    `loyalty_point_earn` DECIMAL(15,3) DEFAULT 0.000,
    `is_promo_item` VARCHAR(10) DEFAULT 'No',
    `promo_parent_id` BIGINT UNSIGNED DEFAULT NULL,
    `item_seller_id` BIGINT UNSIGNED DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`sales_id`) REFERENCES `sales`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`item_id`) REFERENCES `items`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`promo_parent_id`) REFERENCES `sale_details`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`item_seller_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale_payments` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `sale_id` BIGINT UNSIGNED DEFAULT NULL,
    `payment_id` BIGINT UNSIGNED DEFAULT NULL,
    `date` DATE DEFAULT NULL,
    `amount` DECIMAL(15,3) DEFAULT 0.000,
    `multi_currency` VARCHAR(10) DEFAULT 'No',
    `multi_currency_rate` DECIMAL(15,4) DEFAULT 0.0000,
    `usage_point` DECIMAL(15,3) DEFAULT 0.000,
    `note` TEXT DEFAULT NULL,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `outlet_id` BIGINT UNSIGNED DEFAULT NULL,
    `company_id` BIGINT UNSIGNED DEFAULT 1,
    `del_status` VARCHAR(20) DEFAULT 'Live',
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`payment_id`) REFERENCES `payment_methods`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

