<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RashanKiDukanSetup</AssemblyName>
    <ApplicationIcon>..\Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
